/** Field definitions aligned with Project_Architecture_v2 (18 SQL tables). */

/** xs: 1 col | md: 2 cols | lg: 3 cols */
const grid = {
  half: { xs: 12, md: 6, lg: 6 },
  third: { xs: 12, md: 6, lg: 4 },
  quarter: { xs: 12, md: 6, lg: 4 },
  full: { xs: 12 },
  wide: { xs: 12, md: 12, lg: 8 },
};

export const DOMAIN_FIELD_DEFS = {
  businessName: { label: 'Business name', type: 'text', required: true, grid: grid.half },
  vendorCode: { label: 'Vendor code', type: 'text', grid: grid.half },
  username: { label: 'Username', type: 'text', grid: grid.half },
  referral: { label: 'Referral', type: 'text', grid: grid.half },
  vendorRef: { label: 'Vendor', type: 'text', required: true, grid: grid.half },
  contactPerson: { label: 'Contact person', type: 'text', grid: grid.half },
  contact: { label: 'Contact', type: 'text', grid: grid.half },
  commissionPreference: { label: 'Commission preference', type: 'text', grid: grid.half },
  bankDetails: { label: 'Bank details', type: 'textarea', grid: grid.full },

  instituteName: { label: 'Institute name', type: 'text', required: true, grid: grid.half },
  vendorId: { label: 'Vendor name', type: 'api-select', required: true, grid: grid.half },
  primaryColour: { label: 'Primary colour', type: 'text', grid: grid.quarter },
  secondaryColour: { label: 'Secondary colour', type: 'text', grid: grid.quarter },
  primaryColor: { label: 'Primary color', type: 'text', grid: grid.half },
  secondaryColor: { label: 'Secondary color', type: 'text', grid: grid.half },
  logoUrl: { label: 'Logo URL', type: 'text', grid: grid.half },
  dueDate: { label: 'Due date', type: 'date', grid: grid.quarter },
  websiteUrl: { label: 'Website URL', type: 'text', grid: grid.half },
  city: { label: 'City', type: 'text', grid: grid.third },
  state: { label: 'State', type: 'text', grid: grid.third },
  address: { label: 'Address', type: 'textarea', grid: grid.wide },
  serviceTypes: { label: 'Service types', type: 'text', grid: grid.half },
  serviceType: { label: 'Service type', type: 'text', grid: grid.half },
  isPublic: { label: 'Is public', type: 'checkbox', grid: grid.half },
  contactEmail: { label: 'Contact email', type: 'email', grid: grid.half },
  contactPhone: { label: 'Contact phone', type: 'text', grid: grid.half },
  isPublished: { label: 'Published to portal', type: 'select', options: ['Yes', 'No'], grid: grid.third },

  studentId: { label: 'Select student', type: 'api-select', required: true, grid: grid.full },
  fullName: { label: 'Full name', type: 'text', required: true, grid: grid.half },
  enrollmentNumber: { label: 'Enrolment number', type: 'text', grid: grid.half },
  instituteId: { label: 'Institute', type: 'api-select', required: true, grid: grid.half },
  courseId: { label: 'Course', type: 'api-select', required: true, grid: grid.half },
  enrolmentStatus: {
    label: 'Enrolment status',
    type: 'select',
    options: ['Interested', 'Applied', 'Enrolled', 'Dropped'],
    grid: grid.third,
  },

  invoiceNumber: { label: 'Invoice number', type: 'text', required: true, grid: grid.half },
  totalAmount: { label: 'Total amount', type: 'number', grid: grid.quarter },
  rejectionReason: { label: 'Rejection reason', type: 'textarea', grid: grid.wide },

  ruleType: {
    label: 'Rule type',
    type: 'select',
    options: ['StudentOverdue', 'InstituteSheet', 'InvoiceDue', 'AgreementExpiry'],
    grid: grid.half,
  },
  triggerAfterDays: { label: 'Trigger after (days)', type: 'number', grid: grid.quarter },
  intervalDays: { label: 'Repeat interval (days)', type: 'number', grid: grid.quarter },
  isActive: { label: 'Active', type: 'select', options: ['Yes', 'No'], grid: grid.third },

  templateName: { label: 'Template name', type: 'text', required: true, grid: grid.half },
  subject: { label: 'Email subject', type: 'text', grid: grid.half },
  bodyHtml: { label: 'Body (HTML)', type: 'textarea', grid: grid.full },
  category: {
    label: 'Category',
    type: 'select',
    options: ['Reminder', 'Invoice', 'OTP', 'General'],
    grid: grid.third,
  },

  roleName: {
    label: 'Role',
    type: 'select',
    options: ['Admin', 'Accounting', 'Consultant', 'Vendor'],
    grid: grid.third,
  },
  designation: { label: 'Designation', type: 'text', grid: grid.half },
  department: { label: 'Department', type: 'text', grid: grid.half },
  joiningDate: { label: 'Joining date', type: 'date', grid: grid.quarter },

  workDate: { label: 'Work date', type: 'date', grid: grid.quarter },
  checkIn: { label: 'Check-in', type: 'text', grid: grid.quarter },
  checkOut: { label: 'Check-out', type: 'text', grid: grid.quarter },

  taskTitle: { label: 'Task title', type: 'text', required: true, grid: grid.half },
  taskDescription: { label: 'Description', type: 'textarea', grid: grid.full },
  dueDate: { label: 'Due date', type: 'date', grid: grid.quarter },
  priority: {
    label: 'Priority',
    type: 'select',
    options: ['Low', 'Medium', 'High', 'Urgent'],
    grid: grid.third,
  },
  taskStatus: {
    label: 'Status',
    type: 'select',
    options: ['Open', 'InProgress', 'Done', 'Cancelled'],
    grid: grid.third,
  },
  relatedEntityType: {
    label: 'Related entity',
    type: 'select',
    options: ['Vendor', 'Institute', 'Student', 'Invoice'],
    grid: grid.half,
  },
  assignedTo: { label: 'Assigned to', type: 'text', grid: grid.half },

  vendorStatus: {
    label: 'Status',
    type: 'select',
    options: ['Pending', 'Active', 'Disabled', 'Suspended'],
    grid: grid.third,
  },
  instituteStatus: {
    label: 'Status',
    type: 'select',
    options: ['Active', 'Inactive', 'Suspended'],
    grid: grid.third,
  },
  invoiceStatus: {
    label: 'Status',
    type: 'select',
    options: ['Draft', 'PendingApproval', 'Approved', 'Rejected'],
    grid: grid.third,
  },
  paymentStatus: {
    label: 'Status',
    type: 'select',
    options: ['Pending', 'Partial', 'Paid'],
    grid: grid.third,
  },
  scrapeStatus: {
    label: 'Status',
    type: 'select',
    options: ['Queued', 'Running', 'Done', 'Failed'],
    grid: grid.third,
  },
  commissionStatus: {
    label: 'Status',
    type: 'select',
    options: ['Pending', 'Approved', 'Paid'],
    grid: grid.third,
  },

  rateType: { label: 'Rate type', type: 'select', options: ['Percentage', 'Fixed'], grid: grid.quarter },
  rate: { label: 'Rate', type: 'number', grid: grid.quarter },
  effectiveFrom: { label: 'Effective from', type: 'date', grid: grid.quarter },
  effectiveTo: { label: 'Effective to', type: 'date', grid: grid.quarter },
  earnedAmount: { label: 'Earned amount', type: 'number', grid: grid.quarter },
  amountDue: { label: 'Amount due', type: 'number', required: true, grid: grid.quarter },
  amountPaid: { label: 'Amount paid', type: 'number', grid: grid.quarter },

  scheduledAt: { label: 'Scheduled at', type: 'date', grid: grid.half },
  errorMessage: { label: 'Error message', type: 'textarea', grid: grid.wide },

  email: { label: 'Email', type: 'email', grid: grid.half },
  phone: { label: 'Phone', type: 'text', required: true, grid: grid.half },
  notes: { label: 'Notes', type: 'textarea', grid: grid.wide },
  description: { label: 'Description', type: 'textarea', grid: grid.wide },
};

export const DOMAIN_RESOURCES = {
  vendors: {
    singular: 'Vendor',
    plural: 'Vendors',
    actionLabel: 'Add Vendor',
    primaryField: 'businessName',
    requiredFields: ['vendorRef', 'phone'],
    sections: [
      {
        title: 'Vendor & institute',
        description: 'Link vendor account to institute profile.',
        fields: ['vendorRef', 'instituteName', 'vendorStatus'],
      },
      {
        title: 'Branding',
        description: 'Portal appearance and public URLs.',
        fields: ['websiteUrl', 'logoUrl', 'primaryColor', 'secondaryColor'],
      },
      {
        title: 'Location & services',
        description: 'Address and service offerings.',
        fields: ['address', 'city', 'state', 'serviceType'],
      },
      {
        title: 'Contact',
        description: 'Primary contact and visibility.',
        fields: ['contact', 'email', 'phone', 'isPublic'],
      },
    ],
    columns: [
      { id: 'vendorCode', label: 'Vendor code', field: 'vendorCode' },
      { id: 'username', label: 'Username', field: 'username' },
      { id: 'businessName', label: 'Business name', field: 'businessName' },
      { id: 'contactPerson', label: 'Contact person', field: 'contactPerson' },
      { id: 'email', label: 'Email', field: 'email' },
      { id: 'phone', label: 'Phone', field: 'phone' },
      { id: 'referral', label: 'Referral', field: 'referral' },
      { id: 'vendorStatus', label: 'Status', field: 'vendorStatus' },
    ],
    emptyForm: () => ({
      vendorCode: '', username: '', businessName: '', contactPerson: '', referral: '',
      vendorRef: '', instituteName: '', websiteUrl: '', logoUrl: '', primaryColor: '#3385c6',
      secondaryColor: '#1a2b3d', address: '', city: '', state: '', serviceType: '',
      contact: '', email: '', phone: '', isPublic: 'No', vendorStatus: 'Pending',
    }),
  },
  institutes: {
    singular: 'Institute',
    plural: 'Institutes',
    actionLabel: 'Add Institute',
    primaryField: 'instituteName',
    requiredFields: ['vendorId', 'instituteName'],
    sections: [
      {
        title: 'Institute details',
        description: 'Vendor link, identity, and publishing.',
        fields: ['vendorId', 'instituteName', 'websiteUrl', 'instituteStatus', 'isPublished'],
      },
      {
        title: 'Location & services',
        description: 'Address and service offerings.',
        fields: ['address', 'city', 'state', 'serviceType'],
      },
      { title: 'Contact', description: 'Primary institute contacts.', fields: ['contactEmail', 'contactPhone', 'notes'] },
    ],
    columns: [
      { id: 'vendorName', label: 'Vendor name', field: 'vendorName' },
      { id: 'instituteName', label: 'Institute name', field: 'instituteName' },
      { id: 'address', label: 'Address', field: 'address' },
      { id: 'serviceType', label: 'Service type', field: 'serviceType' },
    ],
    emptyForm: () => ({
      vendorId: '',
      instituteName: '',
      websiteUrl: '',
      instituteStatus: 'Active',
      isPublished: 'No',
      address: '',
      city: '',
      state: '',
      serviceType: '',
      contactEmail: '',
      contactPhone: '',
      notes: '',
    }),
  },
  students: {
    singular: 'Student',
    plural: 'Students',
    actionLabel: 'Add Student',
    primaryField: 'fullName',
    requiredFields: ['fullName', 'phone', 'instituteId', 'courseId', 'amountDue', 'dueDate'],
    sections: [
      { title: 'Student profile', description: 'Registered student after AIH interest.', fields: ['fullName', 'enrollmentNumber', 'enrolmentStatus', 'email'] },
      { title: 'Enrolment', description: 'Institute and course assignment.', fields: ['instituteId', 'courseId', 'phone'] },
      { title: 'Payment schedule', description: 'Outstanding balance tracking.', fields: ['amountDue', 'amountPaid', 'paymentStatus', 'dueDate'] },
      { title: 'Notes', description: 'Internal follow-up notes.', fields: ['notes'] },
    ],
    columns: [
      { id: 'fullName', label: 'Student', field: 'fullName' },
      { id: 'email', label: 'Email', field: 'email' },
      { id: 'phone', label: 'Phone', field: 'phone' },
      { id: 'enrollmentNumber', label: 'Enrolment number', field: 'enrollmentNumber' },
      { id: 'enrolmentStatus', label: 'Enrolment', field: 'enrolmentStatus' },
      { id: 'paymentStatus', label: 'Payment', field: 'paymentStatus' },
    ],
    emptyForm: () => ({
      fullName: '', enrollmentNumber: '', enrolmentStatus: 'Interested', email: '',
      instituteId: '', courseId: '', phone: '',
      amountDue: '', amountPaid: '', paymentStatus: 'Pending', dueDate: '', notes: '',
    }),
  },
  invoices: {
    singular: 'Invoice',
    plural: 'Invoices',
    actionLabel: 'Create Invoice',
    primaryField: 'invoiceNumber',
    requiredFields: ['invoiceNumber'],
    sections: [
      { title: 'Invoice header', description: 'Generated from institute Excel upload.', fields: ['invoiceNumber', 'instituteNameRef', 'invoiceStatus', 'totalAmount'] },
      { title: 'Approval', description: 'Workflow and rejection details.', fields: ['assignedTo', 'rejectionReason', 'notes'] },
    ],
    columns: [
      { id: 'invoiceNumber', label: 'Invoice #', field: 'invoiceNumber' },
      { id: 'instituteNameRef', label: 'Institute', field: 'instituteNameRef' },
      { id: 'invoiceStatus', label: 'Status', field: 'invoiceStatus' },
      { id: 'totalAmount', label: 'Amount', field: 'totalAmount' },
    ],
    emptyForm: () => ({
      invoiceNumber: '', instituteNameRef: '', invoiceStatus: 'Draft', totalAmount: '',
      assignedTo: '', rejectionReason: '', notes: '',
    }),
  },
  reminders: {
    singular: 'Reminder rule',
    plural: 'Reminder rules',
    actionLabel: 'Add Rule',
    primaryField: 'templateName',
    requiredFields: ['ruleType'],
    sections: [
      { title: 'Rule configuration', description: 'Automated email reminder triggers.', fields: ['ruleType', 'triggerAfterDays', 'intervalDays', 'isActive'] },
      { title: 'Template link', description: 'Associated email template.', fields: ['templateName', 'category', 'notes'] },
    ],
    columns: [
      { id: 'ruleType', label: 'Rule type', field: 'ruleType' },
      { id: 'triggerAfterDays', label: 'After (days)', field: 'triggerAfterDays' },
      { id: 'isActive', label: 'Active', field: 'isActive' },
      { id: 'updated', label: 'Updated', field: 'updated' },
    ],
    emptyForm: () => ({
      ruleType: 'StudentOverdue', triggerAfterDays: '7', intervalDays: '3', isActive: 'Yes',
      templateName: '', category: 'Reminder', notes: '',
    }),
  },
  templates: {
    singular: 'Email template',
    plural: 'Email templates',
    actionLabel: 'New Template',
    primaryField: 'templateName',
    requiredFields: ['templateName'],
    sections: [
      { title: 'Template', description: 'Supports {{placeholders}} in subject and body.', fields: ['templateName', 'category', 'subject'] },
      { title: 'Body', description: 'HTML email content.', fields: ['bodyHtml', 'notes'] },
    ],
    columns: [
      { id: 'templateName', label: 'Name', field: 'templateName' },
      { id: 'category', label: 'Category', field: 'category' },
      { id: 'subject', label: 'Subject', field: 'subject' },
      { id: 'updated', label: 'Updated', field: 'updated' },
    ],
    emptyForm: () => ({
      templateName: '', category: 'General', subject: '', bodyHtml: '', notes: '',
    }),
  },
  users: {
    singular: 'User',
    plural: 'Users',
    actionLabel: 'Invite User',
    primaryField: 'fullName',
    requiredFields: ['fullName', 'email'],
    sections: [
      { title: 'Account', description: 'Login credentials and role assignment.', fields: ['fullName', 'email', 'phone', 'roleName'] },
      { title: 'Employment', description: 'Optional employee profile link.', fields: ['designation', 'department', 'joiningDate', 'isActive'] },
    ],
    columns: [
      { id: 'fullName', label: 'Name', field: 'fullName' },
      { id: 'email', label: 'Email', field: 'email' },
      { id: 'roleName', label: 'Role', field: 'roleName' },
      { id: 'updated', label: 'Updated', field: 'updated' },
    ],
    emptyForm: () => ({
      fullName: '', email: '', phone: '', roleName: 'Consultant',
      designation: '', department: '', joiningDate: '', isActive: 'Yes',
    }),
  },
  'work-history': {
    singular: 'Work log',
    plural: 'Work history',
    actionLabel: 'Log Hours',
    primaryField: 'fullName',
    hideDelete: true,
    requiredFields: ['fullName', 'workDate'],
    sections: [
      { title: 'Employee', description: 'Staff member and work date.', fields: ['fullName', 'designation', 'department', 'workDate'] },
      { title: 'Time log', description: 'Check-in, check-out, and calculated hours.', fields: ['checkIn', 'checkOut', 'hoursWorked', 'notes'] },
    ],
    columns: [
      { id: 'workDate', label: 'Date', field: 'workDate' },
      { id: 'fullName', label: 'Member', field: 'fullName' },
      { id: 'workspaces', label: 'Workspaces', field: 'workspaces' },
      { id: 'hoursWorked', label: 'Total time', field: 'hoursWorked' },
      { id: 'productive', label: 'Productive', field: 'productive' },
      { id: 'neutral', label: 'Neutral', field: 'neutral' },
    ],
    emptyForm: () => ({
      fullName: '', designation: '', department: '', workDate: '',
      checkIn: '', checkOut: '', hoursWorked: '', notes: '',
    }),
  },
  tasks: {
    singular: 'Task',
    plural: 'Tasks',
    actionLabel: 'Create Task',
    primaryField: 'taskTitle',
    requiredFields: ['taskTitle'],
    sections: [
      { title: 'Task summary', description: 'What needs to be done and by when.', fields: ['taskTitle', 'priority', 'taskStatus', 'dueDate'] },
      { title: 'Assignment', description: 'Owner and related business entity.', fields: ['assignedTo', 'relatedEntityType', 'fullName'] },
      { title: 'Details', description: 'Full task description.', fields: ['taskDescription', 'notes'] },
    ],
    columns: [
      { id: 'taskTitle', label: 'Task', field: 'taskTitle' },
      { id: 'taskStatus', label: 'Status', field: 'taskStatus' },
      { id: 'priority', label: 'Priority', field: 'priority' },
      { id: 'dueDate', label: 'Due', field: 'dueDate' },
    ],
    emptyForm: () => ({
      taskTitle: '', priority: 'Medium', taskStatus: 'Open', dueDate: '',
      assignedTo: '', relatedEntityType: 'Student', fullName: '', taskDescription: '', notes: '',
    }),
  },
  status_students: {
    singular: 'Enrolment',
    plural: 'Student enrolment',
    actionLabel: 'Update Status',
    primaryField: 'fullName',
    requiredFields: ['studentId', 'fullName', 'phone'],
    sections: [
      { title: 'Enrolment pipeline', description: 'Select a student and update enrolment stage.', fields: ['studentId', 'fullName', 'enrolmentStatus'] },
      { title: 'Contact', description: 'Student communication details.', fields: ['email', 'phone', 'notes'] },
    ],
    columns: [
      { id: 'fullName', label: 'Student', field: 'fullName' },
      { id: 'email', label: 'Email', field: 'email' },
      { id: 'phone', label: 'Phone', field: 'phone' },
      { id: 'enrollmentNumber', label: 'Enrolment number', field: 'enrollmentNumber' },
      { id: 'enrolmentStatus', label: 'Stage', field: 'enrolmentStatus' },
      { id: 'instituteNameRef', label: 'Institute', field: 'instituteNameRef' },
    ],
    emptyForm: () => ({
      studentId: '', fullName: '', enrolmentStatus: 'Applied', email: '', phone: '', notes: '',
    }),
  },
  status_vendors: {
    singular: 'Vendor status',
    plural: 'Vendor statuses',
    actionLabel: 'Update Status',
    primaryField: 'businessName',
    requiredFields: ['businessName'],
    sections: [
      { title: 'Vendor account', description: 'Onboarding and compliance status.', fields: ['businessName', 'vendorCode', 'vendorStatus', 'contactPerson'] },
      { title: 'Review notes', description: 'Internal compliance notes.', fields: ['notes', 'description'] },
    ],
    columns: [
      { id: 'businessName', label: 'Vendor', field: 'businessName' },
      { id: 'vendorStatus', label: 'Status', field: 'vendorStatus' },
      { id: 'vendorCode', label: 'Code', field: 'vendorCode' },
      { id: 'updated', label: 'Updated', field: 'updated' },
    ],
    emptyForm: () => ({
      businessName: '', vendorCode: '', vendorStatus: 'Pending', contactPerson: '', notes: '', description: '',
    }),
  },
  status_institutes: {
    singular: 'Institute status',
    plural: 'Institute statuses',
    actionLabel: 'Update Status',
    primaryField: 'instituteName',
    requiredFields: ['instituteName'],
    sections: [
      { title: 'Institute account', description: 'Partnership and publishing status.', fields: ['instituteName', 'instituteStatus', 'isPublished', 'city'] },
      { title: 'Review notes', description: 'Partnership review notes.', fields: ['notes', 'description'] },
    ],
    columns: [
      { id: 'instituteName', label: 'Institute', field: 'instituteName' },
      { id: 'instituteStatus', label: 'Status', field: 'instituteStatus' },
      { id: 'isPublished', label: 'Published', field: 'isPublished' },
      { id: 'updated', label: 'Updated', field: 'updated' },
    ],
    emptyForm: () => ({
      instituteName: '', instituteStatus: 'Active', isPublished: 'No', city: '', notes: '', description: '',
    }),
  },
  'reports_ai-scraping': {
    singular: 'Scrape job',
    plural: 'AI scraping jobs',
    actionLabel: 'Run Job',
    primaryField: 'instituteName',
    requiredFields: ['instituteName'],
    sections: [
      { title: 'Job details', description: 'AI scraper run for institute website.', fields: ['instituteName', 'scrapeStatus', 'scheduledAt', 'websiteUrl'] },
      { title: 'Results', description: 'Error details if job failed.', fields: ['errorMessage', 'notes'] },
    ],
    columns: [
      { id: 'instituteName', label: 'Institute', field: 'instituteName' },
      { id: 'scrapeStatus', label: 'Status', field: 'scrapeStatus' },
      { id: 'scheduledAt', label: 'Scheduled', field: 'scheduledAt' },
      { id: 'updated', label: 'Updated', field: 'updated' },
    ],
    emptyForm: () => ({
      instituteName: '', scrapeStatus: 'Queued', scheduledAt: '', websiteUrl: '', errorMessage: '', notes: '',
    }),
  },
  reports_receivables: {
    singular: 'Receivable',
    plural: 'Anticipated receivables',
    actionLabel: 'Add Forecast',
    primaryField: 'fullName',
    requiredFields: ['fullName'],
    sections: [
      { title: 'Forecast', description: 'Anticipated commission / receivable entry.', fields: ['fullName', 'instituteNameRef', 'earnedAmount', 'commissionStatus'] },
      { title: 'Rate config', description: 'Commission rate applied to forecast.', fields: ['rateType', 'rate', 'effectiveFrom', 'effectiveTo'] },
      { title: 'Notes', description: 'Forecast assumptions.', fields: ['notes'] },
    ],
    columns: [
      { id: 'fullName', label: 'Reference', field: 'fullName' },
      { id: 'earnedAmount', label: 'Amount', field: 'earnedAmount' },
      { id: 'commissionStatus', label: 'Status', field: 'commissionStatus' },
      { id: 'effectiveFrom', label: 'From', field: 'effectiveFrom' },
    ],
    emptyForm: () => ({
      fullName: '', instituteNameRef: '', earnedAmount: '', commissionStatus: 'Pending',
      rateType: 'Percentage', rate: '', effectiveFrom: '', effectiveTo: '', notes: '',
    }),
  },
  reports_received: {
    singular: 'Payment',
    plural: 'Payments received',
    actionLabel: 'Record Payment',
    primaryField: 'fullName',
    requiredFields: ['fullName'],
    sections: [
      { title: 'Payment received', description: 'Confirmed student or institute payment.', fields: ['fullName', 'instituteNameRef', 'amountPaid', 'paymentStatus'] },
      { title: 'Details', description: 'Payment reference and notes.', fields: ['invoiceNumber', 'dueDate', 'notes'] },
    ],
    columns: [
      { id: 'fullName', label: 'Payer', field: 'fullName' },
      { id: 'amountPaid', label: 'Paid', field: 'amountPaid' },
      { id: 'paymentStatus', label: 'Status', field: 'paymentStatus' },
      { id: 'updated', label: 'Date', field: 'updated' },
    ],
    emptyForm: () => ({
      fullName: '', instituteNameRef: '', amountPaid: '', paymentStatus: 'Paid',
      invoiceNumber: '', dueDate: '', notes: '',
    }),
  },
  reports_dues: {
    singular: 'Due account',
    plural: 'Payment dues',
    actionLabel: 'Send Reminder',
    primaryField: 'fullName',
    requiredFields: ['fullName'],
    sections: [
      { title: 'Outstanding due', description: 'Overdue or pending payment.', fields: ['fullName', 'instituteNameRef', 'amountDue', 'paymentStatus'] },
      { title: 'Follow-up', description: 'Reminder and escalation notes.', fields: ['dueDate', 'assignedTo', 'notes'] },
    ],
    columns: [
      { id: 'fullName', label: 'Account', field: 'fullName' },
      { id: 'amountDue', label: 'Due', field: 'amountDue' },
      { id: 'paymentStatus', label: 'Status', field: 'paymentStatus' },
      { id: 'dueDate', label: 'Due date', field: 'dueDate' },
    ],
    emptyForm: () => ({
      fullName: '', instituteNameRef: '', amountDue: '', paymentStatus: 'Pending',
      dueDate: '', assignedTo: '', notes: '',
    }),
  },
  'ai-tool': {
    singular: 'Scrape config',
    plural: 'AI scraping tool',
    actionLabel: 'Start Scrape',
    primaryField: 'instituteName',
    requiredFields: ['instituteName'],
    sections: [
      { title: 'Scrape target', description: 'Manually trigger institute website scrape.', fields: ['instituteName', 'websiteUrl', 'scrapeStatus'] },
      { title: 'Schedule', description: 'When to run the scrape job.', fields: ['scheduledAt', 'notes'] },
    ],
    columns: [
      { id: 'instituteName', label: 'Institute', field: 'instituteName' },
      { id: 'scrapeStatus', label: 'Status', field: 'scrapeStatus' },
      { id: 'websiteUrl', label: 'URL', field: 'websiteUrl' },
      { id: 'scheduledAt', label: 'Scheduled', field: 'scheduledAt' },
    ],
    emptyForm: () => ({
      instituteName: '', websiteUrl: '', scrapeStatus: 'Queued', scheduledAt: '', notes: '',
    }),
  },
  'vendor-portal': {
    singular: 'Portal record',
    plural: 'Vendor portal',
    actionLabel: 'Update Profile',
    primaryField: 'businessName',
    requiredFields: ['businessName'],
    sections: [
      { title: 'My business', description: 'Vendor portal profile and bank details.', fields: ['businessName', 'vendorCode', 'contactPerson', 'email'] },
      { title: 'Commission & banking', description: 'Payout preferences and bank info.', fields: ['commissionPreference', 'bankDetails', 'phone', 'notes'] },
    ],
    columns: [
      { id: 'businessName', label: 'Business', field: 'businessName' },
      { id: 'vendorCode', label: 'Code', field: 'vendorCode' },
      { id: 'email', label: 'Email', field: 'email' },
      { id: 'updated', label: 'Updated', field: 'updated' },
    ],
    emptyForm: () => ({
      businessName: '', vendorCode: '', contactPerson: '', email: '',
      commissionPreference: '', bankDetails: '', phone: '', notes: '',
    }),
  },
  'institutes-scrapping': {
    singular: 'Institute scrapping record',
    plural: 'Institutes scrapping',
    actionLabel: 'Start Scraping',
    primaryField: 'instituteName',
    requiredFields: ['instituteName', 'websiteUrl'],
    sections: [
      {
        title: 'Institute details',
        description: 'Institute name and main website homepage URL. Programs pages are discovered automatically.',
        fields: ['instituteName', 'websiteUrl'],
      },
    ],
    columns: [
      { id: 'instituteName', label: 'Institute name', field: 'instituteName' },
      { id: 'websiteUrl', label: 'Website URL', field: 'websiteUrl' },
    ],
    emptyForm: () => ({
      instituteName: '',
      websiteUrl: '',
    }),
  },
};
